### ISSUE TITLE
Question: official add-ons in the Wiki

### ISSUE THREAD

**Issue by siaynoq** [Slimefun/Slimefun-Wiki#44]
## Description
I was wondering if official Add-Ons (e.g. ExoticGarden) related information should be added to the articles (marked clearly as "extra content"). E.g. it would be great to list the plants which produce Dusts

**Comment by TheBusyBiscuit** [comment]
As long as it is clearly marked as information related to *Addons* and is beneficial to the end user, I don't see any reason why that info shouldn't be mentioned on the wiki.

Also please ask questions like that on our discord server, if possible, it's much easier to manage requests like this there, we have a designated #questions channel and around 2000 people who could potentially answer these questions. It also wouldn't pollute the Issue Tracker as much.
