### ISSUE TITLE
BlockUseHandler

### ISSUE THREAD

**Issue by MothGirlMusic** [Slimefun/Slimefun-Wiki#51]
## Mistake

BlockUseHandler doesn't exist anymore and ItemUseHandler is depreciated.
![Bildschirmfoto 2020-07-22 um 20 37 17](https://user-images.githubusercontent.com/1746550/88242451-3b778400-cc5b-11ea-9882-e5911f4cb517.png)

## My proposed solution

correct the handler to whatever it was changed to

## Wiki page

4a right click with item or click on a block [ItemUseHandler and BlockUseHandler]

## Slimefun Version

  		<groupId>com.github.TheBusyBiscuit</groupId>
  		<artifactId>Slimefun4</artifactId>
  		<version>master-RC-7-ga1952ed-1279</version>

**Comment by TheBusyBiscuit** [comment]
They both still exist and are not deprecated.
You are importing them from the wrong location, they are in `io.github.thebusybiscuit.slimefun4.core.handlers`

Also, you are building against an insanely old version, use "RC-14" as the version.
